### PR TITLE
Adding more logic and speeding up the task completion

### PR DESCRIPTION
**Pull request by neeodev**

### CODE REVIEW

**Comment by neeodev** [comment]
This fix the consummable adding only 1 item to the slot and make your character can beat lich now

**Comment by vertrue** [comment]
thanks for PR, looks nice

for now I do not have time to deal with current bugs and features in this project, so thank you so much for your contributions!

**Review by vertrue — APPROVED** [review]

**Comment by vertrue** [comment]
merge when ready, please

**Comment by neeodev** [comment]
I don't have write access i cannot merge for you 

> merge when ready, please

**Comment by vertrue** [comment]
sure, sorry

**Pull request merged**
